package api

const (
	ColumnFormatTypeAttachments string = "attachments"
	ColumnFormatTypeButton      string = "button"
	ColumnFormatTypeCanvas      string = "canvas"
	ColumnFormatTypeCheckbox    string = "checkbox"
	ColumnFormatTypeCurrency    string = "currency"
	ColumnFormatTypeDate        string = "date"
	ColumnFormatTypeDateTime    string = "dateTime"
	ColumnFormatTypeDuration    string = "duration"
	ColumnFormatTypeEmail       string = "email"
	ColumnFormatTypeImage       string = "image"
	ColumnFormatTypeLookup      string = "lookup"
	ColumnFormatTypeNumber      string = "number"
	ColumnFormatTypeOther       string = "other"
	ColumnFormatTypePackObject  string = "packObject"
	ColumnFormatTypePercent     string = "percent"
	ColumnFormatTypePerson      string = "person"
	ColumnFormatTypeReaction    string = "reaction"
	ColumnFormatTypeScale       string = "scale"
	ColumnFormatTypeSelect      string = "select"
	ColumnFormatTypeSlider      string = "slider"
	ColumnFormatTypeText        string = "text"
	ColumnFormatTypeTime        string = "time"
)
